version: "3"

# Services
services:

    # NGINX Service
    webserver-nginx:
        image:  "${REGISTRY_HOST}/company-yii2-blog-web-server"
        build:
            context:  "./nginx"
            dockerfile: "Dockerfile"
        container_name: webserver-nginx
        ports:
            - "${WEB_SERVER_PORT}:80"
        volumes:
            - "./yii2/:/var/www/html"
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/ssl/:/etc/nginx/ssl/
        depends_on:
            - php-yii2
        networks:
            - company-network

    # Adminer Service
    adminer:
        image:  "${REGISTRY_HOST}/company-yii2-blog-adminer"
        build:
            context:  "./adminer/"
            dockerfile:  "Dockerfile"
        container_name: adminer
        depends_on:
            - db
        environment:
            ADMINER_DEFAULT_SERVER: db
            ADMINER_DEFAULT_DB_DRIVER: mysql
            ADMINER_DEFAULT_DB_HOST: mysql
            ADMINER_DEFAULT_DB_NAME: adminer
            ADMINER_DESIGN: nette
            ADMINER_PLUGINS: tables-filter tinymce
        ports:
            - "${ADMINER_PORT}:8080"

    # MYSQL Service
    db:
        image:  "${REGISTRY_HOST}/company-yii2-blog-db"
        build:
            context:  "./mysql/"
            dockerfile:  "Dockerfile"
        container_name: db
        tty: false
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - company-volumes:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - company-network
        ports:
            - ${DB_PORT}:3306

    # PHP App Service
    php-yii2:
        image:  "${REGISTRY_HOST}/company-yii2-blog-php-yii2"
        build:
            context:  "."
            dockerfile: "./php/Dockerfile"
        container_name: php-yii2
        tty: true
        working_dir: /var/www/html
        env_file:
            - .env
        volumes:
            - "./yii2/:/var/www/html"
            - "./README.md:/var/www/html/README.md"
        networks:
            - company-network
        depends_on:
            - db

# Docker Networks
networks:
    company-network:
        driver: bridge

# Docker Volumes
volumes:
    company-volumes:
        driver: local